# This is a basic workflow to help you get started with Actions

name: CI

on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_MOVER_TOKEN }}"
        project-url: "https://github.com/bounty1342/bounty1342/projects/1"
        column-name: "To do"
        label-name: "todo"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_MOVER_TOKEN }}"
        project-url: "https://github.com/bounty1342/bounty1342/projects/1"
        column-name: "In Progress"
        label-name: "wip"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_MOVER_TOKEN }}"
        project-url: "https://github.com/bounty1342/bounty1342/projects/1"
        column-name: "To Review"
        label-name: "To Review"
        columns-to-ignore: "*"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_MOVER_TOKEN }}"
        project-url: "https://github.com/bounty1342/bounty1342/projects/1"
        column-name: "Done"
        label-name: "Done"
        columns-to-ignore: "*"
